// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFNu4VO4G_nCEbnK76nSlWcB4Fd7uhpY4',
    appId: '1:185066465246:web:d4389b347586d26e175f4f',
    messagingSenderId: '185066465246',
    projectId: 'jobbed-184a6',
    authDomain: 'jobbed-184a6.firebaseapp.com',
    storageBucket: 'jobbed-184a6.appspot.com',
    measurementId: 'G-EPRRKRG4GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNOHQ7oY3J_00X4ympR6BHUWkuxbogUYw',
    appId: '1:185066465246:android:240d948badcf50f7175f4f',
    messagingSenderId: '185066465246',
    projectId: 'jobbed-184a6',
    storageBucket: 'jobbed-184a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxq_tgYBAhBPxyWW6jHIhtAiS93hv9nJM',
    appId: '1:185066465246:ios:87b1ef998843e47f175f4f',
    messagingSenderId: '185066465246',
    projectId: 'jobbed-184a6',
    storageBucket: 'jobbed-184a6.appspot.com',
    iosBundleId: 'com.example.jobbedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxq_tgYBAhBPxyWW6jHIhtAiS93hv9nJM',
    appId: '1:185066465246:ios:94188ceab6ed6347175f4f',
    messagingSenderId: '185066465246',
    projectId: 'jobbed-184a6',
    storageBucket: 'jobbed-184a6.appspot.com',
    iosBundleId: 'com.example.jobbedApp.RunnerTests',
  );
}
